spring:
  datasource:
    url: jdbc:h2:mem:leetcode
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        type.descriptor.sql: true

logging:
  level:
    org.hibernate.type.descriptor.sql: trace